version: "3.9"
services:
  # Indexers
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true
    volumes:
      - ./config/jackett:/config
      - /home/fs144/Drives/Data/Torrents:/downloads
    network_mode: "service:vpn"
    restart: unless-stopped

  # flaresolverr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   environment:
  #     - LOG_LEVEL=${LOG_LEVEL:-info}
  #     - LOG_HTML=${LOG_HTML:-false}
  #     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
  #     - TZ=Asia/Kolkata
  #   ports:
  #     - 8191:8191
  #   restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config/prowlarr:/config
    network_mode: "service:vpn"
    restart: unless-stopped

  # Media Gatherer and Downloaders
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config/sonarr:/config
      - /home/fs144/Drives/Data/Entertainment/Videos/Series:/tv #optional
      - /home/fs144/Drives/Data/Torrents:/downloads #optional
    network_mode: "service:vpn"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config/radarr:/config
      - /home/fs144/Drives/Data/Entertainment/Videos/Movies:/movies #optional
      - /home/fs144/Drives/Data/Torrents:/downloads #optional
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config/readarr:/config
      - /home/fs144/Drives/Data/Entertainment/Literature/Books:/books #optional
      - /home/fs144/Drives/Data/Downloads:/downloads #optional
    restart: unless-stopped

  whisparr:
    container_name: whisparr
    image: cr.hotio.dev/hotio/whisparr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - ./config/whisparr:/config

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - /home/fs144/Drives/Data/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # Streaming and Access

  jellyfin:
    image: lscr.io/linuxserver/jellyfin

    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional

    volumes:
      - ./config/jellyfin:/config
      - /home/fs144/Drives/Data/Entertainment/Videos/Series:/data/tvshows
      - /home/fs144/Drives/Data/Entertainment/Videos/Movies:/data/movies
      - /home/fs144/Drives/Data/Entertainment/Literature/Books:/data/books
      - /home/fs144/Drives/Data/Entertainment/Literature/Manga:/data/manga
      - /home/fs144/Drives/Data/Entertainment/Literature/Light Novels:/data/ln

    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

    restart: unless-stopped

  kavita:
    image: kizaing/kavita:latest
    volumes:
      - ./config/kavita:/kavita/config
      - /home/fs144/Drives/Data/Entertainment/Literature/Manga:/manga
      - /home/fs144/Drives/Data/Entertainment/Literature/Books:/books
      - /home/fs144/Drives/Data/Entertainment/Literature/Light Novels:/lightnovels
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Putting Everything behind a VPN
  vpn:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - FREE_ONLY=on
    ports:
      - 9117:9117 # Jackett
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8787:8787 # Readarr
      - 6969:6969 # Whisparr
    restart: "unless-stopped"
